# Generated by Django 3.2.9 on 2021-11-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('copyright', models.CharField(max_length=128)),
                ('last_build_date', models.DateTimeField()),
                ('image', models.URLField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reader_app.category')),
            ],
            options={
                'ordering': ['-last_build_date'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('link', models.URLField()),
                ('guid', models.CharField(max_length=64)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader_app.channel')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
