# Generated by Django 3.2.9 on 2021-11-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('reader_app', '0004_alter_content_guid'), ('reader_app', '0005_alter_content_guid')]

    dependencies = [
        ('reader_app', '0003_alter_channel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='guid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='content',
            name='guid',
            field=models.CharField(max_length=255),
        ),
    ]
