# Generated by Django 3.2.9 on 2021-11-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader_app', '0004_alter_content_guid_squashed_0005_alter_content_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default='test_slug', max_length=128),
            preserve_default=False,
        ),
    ]
