# Generated by Django 3.2.9 on 2021-12-01 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reader_app', '0005_channel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
